#!/usr/bin/env python3
"""Generate NeverExtensions SDK protocol types from sdk/api/extension-host-protocol.json.

The generator intentionally supports only the small, auditable primitive type vocabulary
used by the Host/Admin/Desktop protocol. Generated files are deterministic.
"""
from __future__ import annotations

import json
import re
import subprocess
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
SPEC = ROOT / "sdk/api/extension-host-protocol.json"
OPENAPI = ROOT / "schemas/openapi.yaml"


def go_type(t: str) -> str:
    return {
        "string": "string",
        "integer": "int",
        "boolean": "bool",
        "object": "map[string]any",
        "string[]": "[]string",
    }[t]


def ts_type(t: str) -> str:
    return {
        "string": "string",
        "integer": "number",
        "boolean": "boolean",
        "object": "Record<string, unknown>",
        "string[]": "string[]",
    }[t]


def rust_type(t: str) -> str:
    return {
        "string": "String",
        "integer": "i64",
        "boolean": "bool",
        "object": "serde_json::Map<String, serde_json::Value>",
        "string[]": "Vec<String>",
    }[t]


def go_name(name: str) -> str:
    parts = name.replace("-", "_").split("_")
    return "".join(p[:1].upper() + p[1:] for p in parts)


def rust_field_name(name: str) -> str:
    return re.sub(r"(?<!^)(?=[A-Z])", "_", name).lower()


def emit_go(spec: dict) -> str:
    lines = [
        "// Code generated by scripts/sdk/generate-types.py; DO NOT EDIT.",
        "package neverextensions",
        "",
        f'const HostProtocolVersion = "{spec["hostProtocolVersion"]}"',
        f'const ExtensionAPIVersion = "{spec["extensionApiVersion"]}"',
        "",
    ]
    for name, fields in spec["types"].items():
        if name in {"AdminContext", "DesktopContext"}:
            continue
        lines.append(f"type {name} struct {{")
        for field, typ in fields.items():
            lines.append(f'\t{go_name(field)} {go_type(typ)} `json:"{field},omitempty"`')
        lines.append("}")
        lines.append("")
    return "\n".join(lines)


def emit_ts(spec: dict, context: str) -> str:
    protocol_key = "adminProtocolVersion" if context == "admin" else "desktopProtocolVersion"
    wanted = "AdminContext" if context == "admin" else "DesktopContext"
    lines = [
        "// Code generated by scripts/sdk/generate-types.py; DO NOT EDIT.",
        f"export const PROTOCOL_VERSION = '{spec[protocol_key]}' as const;",
        f"export const EXTENSION_API_VERSION = '{spec['extensionApiVersion']}' as const;",
        "",
    ]
    fields = spec["types"][wanted]
    body = "; ".join(f"{k}: {ts_type(v)}" for k, v in fields.items())
    lines.append(f"export type {wanted} = {{ {body} }};")
    lines.append("")
    lines.append("export type RPCRequest = { protocol: typeof PROTOCOL_VERSION; type: 'rpc.request'; id: string; method: string; params: unknown };")
    lines.append("export type RPCResponse = { protocol: typeof PROTOCOL_VERSION; type: 'rpc.response'; id: string; result?: unknown; error?: string };")
    return "\n".join(lines) + "\n"


def emit_rust(spec: dict) -> str:
    fields = spec["types"]["DesktopContext"]
    lines = [
        "// Code generated by scripts/sdk/generate-types.py; DO NOT EDIT.",
        "use serde::{Deserialize, Serialize};",
        "",
        f'pub const DESKTOP_PROTOCOL_VERSION: &str = "{spec["desktopProtocolVersion"]}";',
        f'pub const EXTENSION_API_VERSION: &str = "{spec["extensionApiVersion"]}";',
        "",
        "#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]",
        "#[serde(rename_all = \"camelCase\")]",
        "pub struct DesktopContext {",
    ]
    for field, typ in fields.items():
        lines.append(f"    pub {rust_field_name(field)}: {rust_type(typ)},")
    lines.extend(["}", ""])
    return "\n".join(lines)




def extension_openapi_document() -> dict:
    return json.loads(OPENAPI.read_text(encoding="utf-8"))


def extension_component_schemas(doc: dict) -> dict[str, dict]:
    schemas = doc.get("components", {}).get("schemas", {})
    selected = {name for name in schemas if name.startswith("Extension") or name.startswith("DesktopExtension")}

    def refs(value):
        if isinstance(value, dict):
            ref = value.get("$ref")
            if isinstance(ref, str) and ref.startswith("#/components/schemas/"):
                yield ref.split("/")[-1]
            for child in value.values():
                yield from refs(child)
        elif isinstance(value, list):
            for child in value:
                yield from refs(child)

    for path, methods in doc.get("paths", {}).items():
        if "extension" not in path.lower():
            continue
        for method, operation in methods.items():
            if method.lower() in {"get", "post", "put", "patch", "delete"}:
                selected.update(refs(operation.get("requestBody", {})))

    pending = list(selected)
    while pending:
        name = pending.pop()
        schema = schemas.get(name)
        if not isinstance(schema, dict):
            continue
        for ref_name in refs(schema):
            if ref_name not in selected:
                selected.add(ref_name)
                pending.append(ref_name)
    return {name: schemas[name] for name in sorted(selected) if name in schemas}


def ts_schema_type(schema: dict) -> str:
    if "$ref" in schema:
        return schema["$ref"].split("/")[-1]
    if "const" in schema:
        return json.dumps(schema["const"])
    if "enum" in schema:
        return " | ".join(json.dumps(v) for v in schema["enum"])
    typ = schema.get("type")
    if isinstance(typ, list):
        non_null = [x for x in typ if x != "null"]
        base = ts_schema_type({**schema, "type": non_null[0] if non_null else "object"})
        return base + " | null"
    if typ == "string": return "string"
    if typ in {"integer", "number"}: return "number"
    if typ == "boolean": return "boolean"
    if typ == "array": return f"Array<{ts_schema_type(schema.get('items', {}))}>"
    if typ == "object":
        props = schema.get("properties", {})
        if props:
            required = set(schema.get("required", []))
            parts = []
            for name, child in props.items():
                optional = "" if name in required else "?"
                parts.append(f"{json.dumps(name)}{optional}: {ts_schema_type(child)}")
            if schema.get("additionalProperties") is True:
                parts.append("[key: string]: unknown")
            return "{ " + "; ".join(parts) + " }"
        if schema.get("additionalProperties"):
            ap = schema["additionalProperties"]
            return f"Record<string, {ts_schema_type(ap) if isinstance(ap, dict) else 'unknown'}>"
        return "Record<string, unknown>"
    return "unknown"


def emit_openapi_component_ts(doc: dict) -> str:
    schemas = extension_component_schemas(doc)
    lines = ["// Code generated by scripts/sdk/generate-types.py from canonical OpenAPI components; DO NOT EDIT."]
    for name, schema in schemas.items():
        lines.append(f"export type {name} = {ts_schema_type(schema)};")
    lines.append("")
    return "\n".join(lines)


def go_schema_type(schema: dict) -> str:
    if "$ref" in schema: return schema["$ref"].split("/")[-1]
    typ = schema.get("type")
    if isinstance(typ, list):
        non_null = [x for x in typ if x != "null"]
        return go_schema_type({**schema, "type": non_null[0] if non_null else "object"})
    if typ == "string": return "string"
    if typ == "integer": return "int64"
    if typ == "number": return "float64"
    if typ == "boolean": return "bool"
    if typ == "array": return "[]" + go_schema_type(schema.get("items", {}))
    if typ == "object": return "map[string]any"
    return "any"


def emit_openapi_component_go(doc: dict) -> str:
    schemas = extension_component_schemas(doc)
    lines = ["// Code generated by scripts/sdk/generate-types.py from canonical OpenAPI components; DO NOT EDIT.", "package neverextensions", ""]
    for name, schema in schemas.items():
        if schema.get("type") != "object" or not schema.get("properties"):
            lines.append(f"type {name} {go_schema_type(schema)}")
            lines.append("")
            continue
        required = set(schema.get("required", []))
        lines.append(f"type {name} struct {{")
        for field, child in schema["properties"].items():
            tag = field if field in required else field + ",omitempty"
            lines.append(f'\t{go_name(field)} {go_schema_type(child)} `json:"{tag}"`')
        lines.extend(["}", ""])
    return "\n".join(lines)


def request_schema_for_operation(operation: dict) -> dict | None:
    body = operation.get("requestBody", {}).get("content", {}).get("application/json", {}).get("schema")
    return body if isinstance(body, dict) else None


def emit_openapi_request_map_ts(doc: dict, ops: list[dict[str, str]]) -> str:
    operation_index = {}
    for path, methods in doc.get("paths", {}).items():
        for method, operation in methods.items():
            if isinstance(operation, dict) and operation.get("operationId"):
                operation_index[operation["operationId"]] = operation
    lines = ["// Code generated by scripts/sdk/generate-types.py from canonical OpenAPI request bodies; DO NOT EDIT.", "import type * as Components from './api-types-generated';", "", "export interface NeverExtensionsAPIRequestMap {"]
    for item in ops:
        schema = request_schema_for_operation(operation_index.get(item["id"], {}))
        typ = "undefined"
        if schema:
            if "$ref" in schema:
                typ = "Components." + schema["$ref"].split("/")[-1]
            else:
                typ = ts_schema_type(schema)
        lines.append(f"  {json.dumps(item['id'])}: {typ};")
    lines.extend(["}", ""])
    return "\n".join(lines)

def extension_openapi_operations() -> list[dict[str, str]]:
    # canonical OpenAPI is serialized as JSON despite its .yaml filename
    doc = json.loads(OPENAPI.read_text(encoding="utf-8"))
    items: list[dict[str, str]] = []
    for path, methods in doc.get("paths", {}).items():
        if "extension" not in path.lower():
            continue
        for method, operation in methods.items():
            if method.lower() not in {"get", "post", "put", "patch", "delete"}:
                continue
            op_id = operation.get("operationId")
            if op_id:
                items.append({"id": op_id, "method": method.upper(), "path": path})
    return sorted(items, key=lambda x: x["id"])


def emit_openapi_ts(ops: list[dict[str, str]]) -> str:
    ids = " | ".join(json.dumps(item["id"]) for item in ops) or "never"
    lines = [
        "// Code generated by scripts/sdk/generate-types.py from schemas/openapi.yaml; DO NOT EDIT.",
        f"export type NeverExtensionsAPIOperationId = {ids};",
        "export type NeverExtensionsAPIOperation = { method: 'GET'|'POST'|'PUT'|'PATCH'|'DELETE'; path: string };",
        "export const NEVEREXTENSIONS_API_OPERATIONS: Record<NeverExtensionsAPIOperationId, NeverExtensionsAPIOperation> = {",
    ]
    for item in ops:
        lines.append(f"  {json.dumps(item['id'])}: {{ method: {json.dumps(item['method'])} as NeverExtensionsAPIOperation['method'], path: {json.dumps(item['path'])} }},")
    lines.extend(["};", "", "// Canonical API payloads use envelope/object schemas; these aliases remain generated and intentionally transport-only.", "export type NeverExtensionsAPIObject = Record<string, unknown>;", "export type NeverExtensionsAPIResponse<T = NeverExtensionsAPIObject> = { data?: T; error?: unknown } & NeverExtensionsAPIObject;", ""] )
    return "\n".join(lines)


def emit_openapi_go(ops: list[dict[str, str]]) -> str:
    lines = [
        "// Code generated by scripts/sdk/generate-types.py from schemas/openapi.yaml; DO NOT EDIT.",
        "package neverextensions",
        "",
        "type APIOperation struct { Method string; Path string }",
        "",
        "var NeverExtensionsAPIOperations = map[string]APIOperation{",
    ]
    for item in ops:
        lines.append(f'\t{json.dumps(item["id"])}: {{Method: {json.dumps(item["method"])}, Path: {json.dumps(item["path"])} }},')
    lines.extend(["}", ""])
    return "\n".join(lines)

def main() -> None:
    spec = json.loads(SPEC.read_text(encoding="utf-8"))
    openapi = extension_openapi_document()
    ops = extension_openapi_operations()
    generated = {
        ROOT / "sdk/backend/go/types_generated.go": emit_go(spec),
        ROOT / "sdk/cli/go/types_generated.go": emit_go(spec),
        ROOT / "sdk/admin/typescript/generated.ts": emit_ts(spec, "admin"),
        ROOT / "sdk/desktop/typescript/generated.ts": emit_ts(spec, "desktop"),
        ROOT / "sdk/desktop/rust/src/generated.rs": emit_rust(spec),
        ROOT / "sdk/admin/typescript/openapi-generated.ts": emit_openapi_ts(ops),
        ROOT / "sdk/desktop/typescript/openapi-generated.ts": emit_openapi_ts(ops),
        ROOT / "sdk/backend/go/openapi_generated.go": emit_openapi_go(ops),
        ROOT / "sdk/cli/go/openapi_generated.go": emit_openapi_go(ops),
        ROOT / "sdk/api/openapi-operations-generated.json": json.dumps(ops, ensure_ascii=False, indent=2) + "\n",
        ROOT / "sdk/admin/typescript/api-types-generated.ts": emit_openapi_component_ts(openapi),
        ROOT / "sdk/desktop/typescript/api-types-generated.ts": emit_openapi_component_ts(openapi),
        ROOT / "sdk/admin/typescript/api-requests-generated.ts": emit_openapi_request_map_ts(openapi, ops),
        ROOT / "sdk/desktop/typescript/api-requests-generated.ts": emit_openapi_request_map_ts(openapi, ops),
        ROOT / "sdk/backend/go/api_types_generated.go": emit_openapi_component_go(openapi),
        ROOT / "sdk/cli/go/api_types_generated.go": emit_openapi_component_go(openapi),
    }
    go_files = []
    for path, data in generated.items():
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(data, encoding="utf-8", newline="\n")
        if path.suffix == ".go":
            go_files.append(str(path))
        print(path.relative_to(ROOT))
    if go_files:
        subprocess.run(["gofmt", "-w", *go_files], check=True, cwd=ROOT)


if __name__ == "__main__":
    main()
