[package]
name = "neverruntime"
version = "0.13.4"
description = "NeverRuntime core library for NeverLauncher"
authors = ["Дмитрий \"SkiF4er\" Ефимов"]
license = "Apache-2.0"
edition = "2021"

[lib]
name = "neverruntime"
path = "src/lib.rs"

[[bin]]
name = "neverruntime"
path = "src/bin/neverruntime.rs"

[[bin]]
name = "neverguard"
path = "src/bin/neverguard.rs"

[dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = "1"
sha2 = "0.10"
hmac = "0.12"
subtle = "2"
hex = "0.4"
regex = "1"
ed25519-dalek = "2"
reqwest = { version = "0.12", features = ["json", "stream", "rustls-tls"], default-features = false }
tokio = { version = "1", features = ["fs", "io-util", "net", "process", "rt-multi-thread", "macros", "sync", "time"] }
rand = "0.8"
zeroize = "1"

[target.'cfg(windows)'.dependencies]
windows-sys = { version = "0.61.2", features = ["Win32_Foundation", "Win32_Security_Cryptography", "Win32_Security_WinTrust", "Win32_System_Diagnostics_ToolHelp", "Win32_System_JobObjects", "Win32_System_SystemServices", "Win32_System_Threading"] }
