// Код сгенерирован scripts/sdk/generate-types.py из schemas/openapi.yaml; НЕ РЕДАКТИРОВАТЬ.
package neverextensions

type APIOperation struct {
	Method string
	Path   string
}

var NeverExtensionsAPIOperations = map[string]APIOperation{
	"delete_admin_extension_updates_pins_by_extensionId":                                  {Method: "DELETE", Path: "/api/v1/admin/extension-updates/pins/{extensionId}"},
	"delete_admin_extensions_by_extensionId_emergency_disable":                            {Method: "DELETE", Path: "/api/v1/admin/extensions/{extensionId}/emergency-disable"},
	"delete_admin_extensions_by_extensionId_permissions_by_permission":                    {Method: "DELETE", Path: "/api/v1/admin/extensions/{extensionId}/permissions/{permission}"},
	"delete_admin_extensions_by_extensionId_secrets_by_secretName":                        {Method: "DELETE", Path: "/api/v1/admin/extensions/{extensionId}/secrets/{secretName}"},
	"get_admin_extension_capabilities":                                                    {Method: "GET", Path: "/api/v1/admin/extension-capabilities"},
	"get_admin_extension_cli_catalog":                                                     {Method: "GET", Path: "/api/v1/admin/extension-cli/catalog"},
	"get_admin_extension_emergency_disables":                                              {Method: "GET", Path: "/api/v1/admin/extension-emergency-disables"},
	"get_admin_extension_events":                                                          {Method: "GET", Path: "/api/v1/admin/extension-events"},
	"get_admin_extension_events_dead_letters":                                             {Method: "GET", Path: "/api/v1/admin/extension-events/dead-letters"},
	"get_admin_extension_events_subscriptions":                                            {Method: "GET", Path: "/api/v1/admin/extension-events/subscriptions"},
	"get_admin_extension_ga_status":                                                       {Method: "GET", Path: "/api/v1/admin/extension-ga/status"},
	"get_admin_extension_hosts":                                                           {Method: "GET", Path: "/api/v1/admin/extension-hosts"},
	"get_admin_extension_hosts_by_extensionId":                                            {Method: "GET", Path: "/api/v1/admin/extension-hosts/{extensionId}"},
	"get_admin_extension_hosts_by_extensionId_logs":                                       {Method: "GET", Path: "/api/v1/admin/extension-hosts/{extensionId}/logs"},
	"get_admin_extension_installs":                                                        {Method: "GET", Path: "/api/v1/admin/extension-installs"},
	"get_admin_extension_installs_by_extensionId":                                         {Method: "GET", Path: "/api/v1/admin/extension-installs/{extensionId}"},
	"get_admin_extension_quarantine":                                                      {Method: "GET", Path: "/api/v1/admin/extension-quarantine"},
	"get_admin_extension_recovery_export":                                                 {Method: "GET", Path: "/api/v1/admin/extension-recovery/export"},
	"get_admin_extension_registry_extensions":                                             {Method: "GET", Path: "/api/v1/admin/extension-registry/extensions"},
	"get_admin_extension_registry_extensions_by_extensionId":                              {Method: "GET", Path: "/api/v1/admin/extension-registry/extensions/{extensionId}"},
	"get_admin_extension_registry_extensions_by_extensionId_versions_by_version":          {Method: "GET", Path: "/api/v1/admin/extension-registry/extensions/{extensionId}/versions/{version}"},
	"get_admin_extension_registry_extensions_by_extensionId_versions_by_version_artifact": {Method: "GET", Path: "/api/v1/admin/extension-registry/extensions/{extensionId}/versions/{version}/artifact"},
	"get_admin_extension_registry_publishers":                                             {Method: "GET", Path: "/api/v1/admin/extension-registry/publishers"},
	"get_admin_extension_registry_publishers_by_publisherId_keys":                         {Method: "GET", Path: "/api/v1/admin/extension-registry/publishers/{publisherId}/keys"},
	"get_admin_extension_trust_policy":                                                    {Method: "GET", Path: "/api/v1/admin/extension-trust/policy"},
	"get_admin_extension_updates_pins":                                                    {Method: "GET", Path: "/api/v1/admin/extension-updates/pins"},
	"get_admin_extension_updates_transactions_by_transactionId":                           {Method: "GET", Path: "/api/v1/admin/extension-updates/transactions/{transactionId}"},
	"get_admin_extensions":                                                                {Method: "GET", Path: "/api/v1/admin/extensions"},
	"get_admin_extensions_by_extensionId":                                                 {Method: "GET", Path: "/api/v1/admin/extensions/{extensionId}"},
	"get_admin_extensions_by_extensionId_permissions":                                     {Method: "GET", Path: "/api/v1/admin/extensions/{extensionId}/permissions"},
	"get_admin_extensions_by_extensionId_secrets":                                         {Method: "GET", Path: "/api/v1/admin/extensions/{extensionId}/secrets"},
	"get_admin_extensions_by_extensionId_ui":                                              {Method: "GET", Path: "/api/v1/admin/extensions/{extensionId}/ui"},
	"get_admin_extensions_by_extensionId_versions":                                        {Method: "GET", Path: "/api/v1/admin/extensions/{extensionId}/versions"},
	"get_admin_extensions_by_extensionId_versions_by_version":                             {Method: "GET", Path: "/api/v1/admin/extensions/{extensionId}/versions/{version}"},
	"get_admin_extensions_catalog":                                                        {Method: "GET", Path: "/api/v1/admin/extensions/catalog"},
	"get_admin_extensions_manager":                                                        {Method: "GET", Path: "/api/v1/admin/extensions/manager"},
	"get_desktop_extensions_by_extensionId_ui":                                            {Method: "GET", Path: "/api/v1/desktop/extensions/{extensionId}/ui"},
	"get_desktop_extensions_catalog":                                                      {Method: "GET", Path: "/api/v1/desktop/extensions/catalog"},
	"post_admin_extension_cli_by_extensionId_invoke":                                      {Method: "POST", Path: "/api/v1/admin/extension-cli/{extensionId}/invoke"},
	"post_admin_extension_ga_reconcile":                                                   {Method: "POST", Path: "/api/v1/admin/extension-ga/reconcile"},
	"post_admin_extension_hosts_by_extensionId_restart":                                   {Method: "POST", Path: "/api/v1/admin/extension-hosts/{extensionId}/restart"},
	"post_admin_extension_hosts_by_extensionId_start":                                     {Method: "POST", Path: "/api/v1/admin/extension-hosts/{extensionId}/start"},
	"post_admin_extension_hosts_by_extensionId_stop":                                      {Method: "POST", Path: "/api/v1/admin/extension-hosts/{extensionId}/stop"},
	"post_admin_extension_installs_by_extensionId_disable":                                {Method: "POST", Path: "/api/v1/admin/extension-installs/{extensionId}/disable"},
	"post_admin_extension_installs_by_extensionId_enable":                                 {Method: "POST", Path: "/api/v1/admin/extension-installs/{extensionId}/enable"},
	"post_admin_extension_installs_by_extensionId_install":                                {Method: "POST", Path: "/api/v1/admin/extension-installs/{extensionId}/install"},
	"post_admin_extension_installs_by_extensionId_rollback":                               {Method: "POST", Path: "/api/v1/admin/extension-installs/{extensionId}/rollback"},
	"post_admin_extension_installs_by_extensionId_uninstall":                              {Method: "POST", Path: "/api/v1/admin/extension-installs/{extensionId}/uninstall"},
	"post_admin_extension_installs_by_extensionId_update":                                 {Method: "POST", Path: "/api/v1/admin/extension-installs/{extensionId}/update"},
	"post_admin_extension_quarantine_by_quarantineId_release":                             {Method: "POST", Path: "/api/v1/admin/extension-quarantine/{quarantineId}/release"},
	"post_admin_extension_recovery_backup":                                                {Method: "POST", Path: "/api/v1/admin/extension-recovery/backup"},
	"post_admin_extension_recovery_import":                                                {Method: "POST", Path: "/api/v1/admin/extension-recovery/import"},
	"post_admin_extension_recovery_restore":                                               {Method: "POST", Path: "/api/v1/admin/extension-recovery/restore"},
	"post_admin_extension_registry_extensions_by_extensionId_versions_by_version_install": {Method: "POST", Path: "/api/v1/admin/extension-registry/extensions/{extensionId}/versions/{version}/install"},
	"post_admin_extension_registry_extensions_by_extensionId_versions_by_version_yank":    {Method: "POST", Path: "/api/v1/admin/extension-registry/extensions/{extensionId}/versions/{version}/yank"},
	"post_admin_extension_registry_publish":                                               {Method: "POST", Path: "/api/v1/admin/extension-registry/publish"},
	"post_admin_extension_registry_publishers":                                            {Method: "POST", Path: "/api/v1/admin/extension-registry/publishers"},
	"post_admin_extension_registry_publishers_by_publisherId_keys":                        {Method: "POST", Path: "/api/v1/admin/extension-registry/publishers/{publisherId}/keys"},
	"post_admin_extension_registry_publishers_by_publisherId_keys_by_fingerprint_revoke":  {Method: "POST", Path: "/api/v1/admin/extension-registry/publishers/{publisherId}/keys/{fingerprint}/revoke"},
	"post_admin_extension_updates_apply":                                                  {Method: "POST", Path: "/api/v1/admin/extension-updates/apply"},
	"post_admin_extension_updates_plan":                                                   {Method: "POST", Path: "/api/v1/admin/extension-updates/plan"},
	"post_admin_extensions_by_extensionId_emergency_disable":                              {Method: "POST", Path: "/api/v1/admin/extensions/{extensionId}/emergency-disable"},
	"post_admin_extensions_by_extensionId_permissions":                                    {Method: "POST", Path: "/api/v1/admin/extensions/{extensionId}/permissions"},
	"post_admin_extensions_by_extensionId_rpc":                                            {Method: "POST", Path: "/api/v1/admin/extensions/{extensionId}/rpc"},
	"post_admin_extensions_versions":                                                      {Method: "POST", Path: "/api/v1/admin/extensions/versions"},
	"post_desktop_extensions_by_extensionId_rpc":                                          {Method: "POST", Path: "/api/v1/desktop/extensions/{extensionId}/rpc"},
	"put_admin_extension_registry_extensions_by_extensionId_channels_by_channel":          {Method: "PUT", Path: "/api/v1/admin/extension-registry/extensions/{extensionId}/channels/{channel}"},
	"put_admin_extension_trust_policy":                                                    {Method: "PUT", Path: "/api/v1/admin/extension-trust/policy"},
	"put_admin_extension_updates_pins_by_extensionId":                                     {Method: "PUT", Path: "/api/v1/admin/extension-updates/pins/{extensionId}"},
	"put_admin_extensions_by_extensionId_secrets_by_secretName":                           {Method: "PUT", Path: "/api/v1/admin/extensions/{extensionId}/secrets/{secretName}"},
}
