#!/usr/bin/env python3
from pathlib import Path
root = Path(__file__).resolve().parents[3]
version = (root / "VERSION").read_text(encoding="utf-8").strip()
if tuple(int(p) for p in version.split(".")[:3]) < (0, 14, 7): raise SystemExit("VERSION is older than 0.14.7")
def read(path): return (root / path).read_text(encoding="utf-8")
def require(text, needles, label):
    missing=[n for n in needles if n not in text]
    if missing: raise SystemExit(f"{label}: missing {missing}")
api_migration=read("services/api/internal/dbmigrate/sql/0027_forge_neoforge_server_bridge_0147.sql")
cli_migration=read("cli/internal/dbmigrate/sql/0027_forge_neoforge_server_bridge_0147.sql")
if api_migration != cli_migration: raise SystemExit("0.14.7 API/CLI Forge/NeoForge migrations differ")
require(api_migration,["server_bridge_nodes_v2_kind_check","'forge'","'neoforge'","'fabric'"],"0.14.7 PostgreSQL migration")
settings=read("settings.gradle.kts")
require(settings,['maven("https://maven.minecraftforge.net/")','maven("https://maven.neoforged.net/releases/")','include("plugins:modloader-family-common")','include("plugins:forge-bridge")','include("plugins:neoforge-bridge")'],"Gradle Forge-family modules")
runtime=read("plugins/modloader-family-common/src/main/java/ru/neverlauncher/bridge/modloader/ModLoaderBridgeRuntime.java")
require(runtime,["new ArrayBlockingQueue<>(256)","new ThreadPoolExecutor.AbortPolicy()","BridgeIntegrity.artifactSha256","NodeIdentity.loadOrCreate","validateJoinAsync","current.api.validateJoin","current.api.heartbeat","validationExecutor.shutdownNow()","heartbeatExecutor.shutdownNow()"],"shared modloader-family production runtime")
forge=read("plugins/forge-bridge/src/main/java/ru/neverlauncher/bridge/forge/NeverLauncherForgeBridge.java")
neo=read("plugins/neoforge-bridge/src/main/java/ru/neverlauncher/bridge/neoforge/NeverLauncherNeoForgeBridge.java")
for text,label,platform in ((forge,"Forge","forge"),(neo,"NeoForge","neoforge")):
    require(text,["PlayerNegotiationEvent","event.enqueueWork(gate)","validateJoinAsync","connection.disconnect",f'"{platform}"'],f"{label} pre-world login gate")
forge_build=read("plugins/forge-bridge/build.gradle.kts")
neo_build=read("plugins/neoforge-bridge/build.gradle.kts")
require(forge_build,['net.minecraftforge.gradle','1.21.1-52.1.16','configurations.create("bridgeRuntime")','implementation(minecraft.dependency("net.minecraftforge:forge:1.21.1-52.1.16"))','add(bridgeRuntime.name, project(":plugins:modloader-family-common"))'],"Forge production build")
require(neo_build,['net.neoforged.moddev','21.1.251','configurations.create("bridgeRuntime")','add(bridgeRuntime.name, project(":plugins:modloader-family-common"))'],"NeoForge production build")
require(read("plugins/forge-bridge/src/main/resources/META-INF/mods.toml"),['displayTest="IGNORE_SERVER_VERSION"','side="SERVER"','versionRange="[1.21.1,1.21.2)"'],"Forge server-only metadata")
require(read("plugins/neoforge-bridge/src/main/resources/META-INF/neoforge.mods.toml"),['displayTest="IGNORE_SERVER_VERSION"','side="SERVER"','versionRange="[1.21.1,1.21.2)"'],"NeoForge server-only metadata")
backend=read("services/api/internal/httpapi/server_bridge.go")
integrity=read("services/api/internal/httpapi/serverbridge_integrity_0135.go")
config=read("services/api/internal/config/config.go")
manifest=read("services/api/internal/httpapi/bridge_plugins.go")
require(backend,['"fabric", "forge", "neoforge"'],"Backend Forge/NeoForge kind enforcement")
require(integrity,["ForgeSHA256","NeoForgeSHA256",'case "forge":','case "neoforge":'],"Forge/NeoForge integrity namespaces")
require(config,["bridgeReleaseRequiresForgeFamily0147","ForgeSHA256","NeoForgeSHA256","для 0.14.7+"],"0.14.7 production release policy")
for kind,descriptor in (("forge","META-INF/mods.toml"),("neoforge","META-INF/neoforge.mods.toml")):
    require(manifest,[f'{{"id": "{kind}"',f'neverlauncher-{kind}-bridge-',f'"descriptor": "{descriptor}"'],f"{kind} manifest")
build=read("scripts/build/bridge-plugins.sh")
require(build,[":plugins:forge-bridge:clean",":plugins:neoforge-bridge:clean","forgeSha256","neoforgeSha256","ModLoaderBridgeRuntime.class","META-INF/mods.toml","META-INF/neoforge.mods.toml"],"Forge/NeoForge release build")
require(read("scripts/release/build-release.sh"),["fabric forge neoforge"],"release bundle Forge/NeoForge artifacts")
require(read("cli/cmd/neverlauncher/release_commands.go"),['"neverlauncher-forge-bridge-" + ver + ".jar"','"neverlauncher-neoforge-bridge-" + ver + ".jar"'],"release verification Forge/NeoForge artifacts")
require(read("scripts/contracts/generate_openapi.py"),['"fabric","forge","neoforge"'],"OpenAPI Forge/NeoForge kinds")
tests=read("services/api/internal/httpapi/serverbridge_forge_neoforge_0147_test.go")
require(tests,["TestForgeNeoForgeKinds0147","TestForgeNeoForgeIntegrityNamespaces0147","TestForgeNeoForgeManifest0147"],"Forge/NeoForge regressions")
e2e=read("e2e/scripts/run-minecraft-e2e.sh"); compose=read("e2e/docker-compose.minecraft-e2e.yml")
require(e2e,["compose up -d velocity bungeecord waterfall spigot paper purpur folia fabric forge neoforge","flow_for_server forge-e2e-p3","flow_for_server neoforge-e2e-p3","forgeNeoForgeServerBridge:true","health-forge.json","health-neoforge.json"],"Forge/NeoForge runtime E2E")
require(compose,["TYPE: FORGE","TYPE: NEOFORGE","FORGE_VERSION: \"52.1.16\"","NEOFORGE_VERSION: \"21.1.251\"","./runtime/plugins/forge:/mods:ro","./runtime/plugins/neoforge:/mods:ro"],"Forge/NeoForge Docker E2E")
migration=read("e2e/scripts/run-forge-neoforge-server-bridge-migration-e2e.sh")
require(migration,["0026_fabric_server_bridge_0146","0027_forge_neoforge_server_bridge_0147","kind IN ('forge','neoforge')","non-canonical kind bypassed constraint"],"0.14.6 -> 0.14.7 migration E2E")
for text,label in ((read("scripts/release/preflight.sh"),"preflight"),(read(".github/workflows/ci.yml"),"CI")):
    require(text,["serverbridge-forge-neoforge-0147.py","run-forge-neoforge-server-bridge-migration-e2e.sh"],f"0.14.7 {label} wiring")
print(f"NeverLauncher 0.14.7 Forge + NeoForge Server Bridge gate: OK ({version})")
