// Code generated by scripts/sdk/generate-types.py; DO NOT EDIT.
package neverextensions

const HostProtocolVersion = "1.0"

type HostEnvironment struct {
	ExtensionId   string `json:"extensionId,omitempty"`
	Version       string `json:"version,omitempty"`
	Scope         string `json:"scope,omitempty"`
	ScopeId       string `json:"scopeId,omitempty"`
	Target        string `json:"target,omitempty"`
	HostUrl       string `json:"hostUrl,omitempty"`
	HostToken     string `json:"hostToken,omitempty"`
	CallbackToken string `json:"callbackToken,omitempty"`
	InstanceId    string `json:"instanceId,omitempty"`
}

type HelloRequest struct {
	ProtocolVersion string `json:"protocolVersion,omitempty"`
	InstanceId      string `json:"instanceId,omitempty"`
	ExtensionId     string `json:"extensionId,omitempty"`
	Pid             int    `json:"pid,omitempty"`
	CallbackUrl     string `json:"callbackUrl,omitempty"`
}

type HelloResponse struct {
	ProtocolVersion         string   `json:"protocolVersion,omitempty"`
	InstanceId              string   `json:"instanceId,omitempty"`
	HeartbeatTimeoutSeconds int      `json:"heartbeatTimeoutSeconds,omitempty"`
	Capabilities            []string `json:"capabilities,omitempty"`
	Events                  []string `json:"events,omitempty"`
	EventProtocolVersion    string   `json:"eventProtocolVersion,omitempty"`
}

type LogRequest struct {
	Level   string         `json:"level,omitempty"`
	Message string         `json:"message,omitempty"`
	Fields  map[string]any `json:"fields,omitempty"`
}

type EventSubscription struct {
	Id        string `json:"id,omitempty"`
	EventType string `json:"eventType,omitempty"`
	Mode      string `json:"mode,omitempty"`
	ProjectId string `json:"projectId,omitempty"`
}
