// Code generated by scripts/sdk/generate-types.py from canonical OpenAPI components; DO NOT EDIT.
export type CreateVersionRequest = { "profileId"?: string; "channel"?: string; "version": string };
export type DesktopExtensionRPCRequest0209 = { "protocol": "neverextensions.desktop-rpc.v1"; "id": string; "method": string; "params"?: Record<string, unknown> };
export type ExtensionCLIInvokeRequest0209 = { "scope": "global" | "project"; "scopeId"?: string; "command": string; "args"?: Array<string> };
export type ExtensionLifecycleWrite = { "version"?: string; "channel"?: string; "scope"?: "global" | "project"; "scopeId"?: string };
export type ExtensionPermissionGrantWrite = { "version"?: string; "scope"?: "global" | "project"; "scopeId"?: string; "permission": string; "reason"?: string };
export type ExtensionRegistryChannelWrite = { "version": string };
export type ExtensionRegistryInstallWrite = { "scope"?: "global" | "project"; "scopeId"?: string };
export type ExtensionRegistryPublisherKeyWrite = { "publicKeyBase64": string; "active"?: boolean };
export type ExtensionRegistryPublisherWrite = { "id": string; "name": string; "active"?: boolean };
export type ExtensionRegistryYankWrite = { "reason": string };
export type ExtensionSecretWrite = { "scope"?: "global" | "project"; "scopeId"?: string; "valueBase64": string };
export type FreeFormObject = Record<string, unknown>;
