// Code generated by scripts/sdk/generate-types.py; DO NOT EDIT.
export const PROTOCOL_VERSION = 'neverextensions.admin-rpc.v1' as const;

export type AdminContext = { extensionId: string; version: string; scope: string; scopeId: string; pageId: string; actionId: string };

export type RPCRequest = { protocol: typeof PROTOCOL_VERSION; type: 'rpc.request'; id: string; method: string; params: unknown };
export type RPCResponse = { protocol: typeof PROTOCOL_VERSION; type: 'rpc.response'; id: string; result?: unknown; error?: string };
