package httpapi

import (
	"net/http"
	"time"
)

func (s Server) registerAuthRoutesV1(mux *http.ServeMux) {
	mux.HandleFunc("POST /api/v1/auth/login", s.authLogin)
	mux.HandleFunc("POST /api/v1/auth/passkeys/login/begin", s.authPasskeyLoginBegin117)
	mux.HandleFunc("POST /api/v1/auth/passkeys/login/complete", s.authPasskeyLoginComplete117)
	mux.HandleFunc("POST /api/v1/auth/passkeys/mfa/complete", s.authPasskeyMFALoginComplete117)
	mux.HandleFunc("POST /api/v1/auth/oidc/{providerId}/begin", s.authOIDCBegin115)
	mux.HandleFunc("POST /api/v1/auth/oidc/{providerId}/complete", s.authOIDCComplete115)
	mux.HandleFunc("GET /api/v1/auth/oidc/{providerId}/start", s.authOIDCStart115)
	mux.HandleFunc("GET /api/v1/auth/oidc/{providerId}/callback", s.authOIDCCallback115)
	mux.HandleFunc("POST /api/v1/auth/microsoft/{providerId}/link/begin", s.authMicrosoftLinkBegin116)
	mux.HandleFunc("POST /api/v1/auth/microsoft/{providerId}/link/complete", s.authMicrosoftLinkComplete116)
	mux.HandleFunc("POST /api/v1/auth/microsoft/{providerId}/logout-url", s.authMicrosoftLogoutURL116)
	mux.HandleFunc("POST /api/v1/auth/providers/{providerId}/credential/refresh", s.authProviderCredentialRefresh116)
	mux.HandleFunc("DELETE /api/v1/auth/providers/{providerId}/credential", s.authProviderCredentialDelete116)
	mux.HandleFunc("POST /api/v1/auth/providers/{providerId}/logout", s.authProviderLogout118)
	mux.HandleFunc("GET /api/v1/auth/providers", s.authProviders112)
	mux.HandleFunc("GET /api/v1/auth/identities", s.authIdentities112)
	mux.HandleFunc("POST /api/v1/auth/refresh", s.authRefresh)
	mux.HandleFunc("POST /api/v1/auth/logout", s.authLogout)
	mux.Handle("GET /api/v1/auth/passkeys", s.requirePermission("project:read", s.authPasskeys117))
	mux.Handle("POST /api/v1/auth/passkeys/register/begin", s.requirePermission("project:read", s.authPasskeyRegisterBegin117))
	mux.Handle("POST /api/v1/auth/passkeys/register/complete", s.requirePermission("project:read", s.authPasskeyRegisterComplete117))
	mux.Handle("POST /api/v1/auth/passkeys/step-up/begin", s.requirePermission("project:read", s.authPasskeyStepUpBegin117))
	mux.Handle("POST /api/v1/auth/passkeys/step-up/complete", s.requirePermission("project:read", s.authPasskeyStepUpComplete117))
	mux.Handle("PATCH /api/v1/auth/passkeys/{credentialId}", s.requirePermission("project:read", s.authPasskeyRename117))
	mux.Handle("DELETE /api/v1/auth/passkeys/{credentialId}", s.requirePermission("project:read", s.authPasskeyDelete117))
	mux.Handle("GET /api/v1/auth/mfa", s.requirePermission("project:read", s.authMFAStatus117))
	mux.Handle("PUT /api/v1/auth/mfa/policy", s.requirePermission("project:read", s.authMFAPolicy117))
	mux.Handle("POST /api/v1/auth/mfa/step-up/totp", s.requirePermission("project:read", s.authMFAStepUpTOTP117))
	mux.Handle("GET /api/v1/auth/accounts", s.requirePermission("project:read", s.authAccounts))
	mux.Handle("GET /api/v1/auth/sessions", s.requirePermission("project:read", s.v1AuthSessions))
	mux.Handle("PATCH /api/v1/auth/sessions/{sessionId}", s.requirePermission("project:read", s.v1AuthRenameSession118))
	mux.Handle("DELETE /api/v1/auth/sessions/{sessionId}", s.requirePermission("project:read", s.v1AuthRevokeOne118))
	mux.Handle("POST /api/v1/auth/sessions/revoke", s.requirePermission("project:read", s.v1AuthRevokeSessions))
	mux.Handle("POST /api/v1/auth/sessions/revoke-others", s.requirePermission("project:read", s.v1AuthRevokeOthers118))
	mux.Handle("POST /api/v1/auth/sessions/logout-all", s.requirePermission("project:read", s.v1AuthRevokeSessions))
	mux.Handle("GET /api/v1/admin/auth/sessions", s.requirePermission("users:manage", s.adminAuthSessions118))
	mux.Handle("POST /api/v1/admin/auth/sessions/revoke", s.requireFreshAuth117("users:manage", "phishing-resistant", 5*time.Minute, s.adminAuthRevokeSessions118))
	mux.Handle("POST /api/v1/admin/auth/providers/{providerId}/sessions/revoke", s.requireFreshAuth117("users:manage", "phishing-resistant", 5*time.Minute, s.adminAuthRevokeProviderSessions118))
	mux.HandleFunc("GET /api/v1/auth/capabilities", s.authCapabilities)
	mux.HandleFunc("GET /api/v1/auth/password-policy", s.authPasswordPolicy)
	mux.HandleFunc("GET /api/v1/auth/session-policy", s.authSessionPolicy)
	mux.Handle("GET /api/v1/auth/roles", s.requirePermission("users:manage", s.authRoles))
	mux.Handle("POST /api/v1/auth/totp/enroll", s.requirePermission("project:read", s.authTOTPEnroll))
	mux.Handle("POST /api/v1/auth/totp/verify", s.requirePermission("project:read", s.authTOTPVerify))
	mux.Handle("POST /api/v1/auth/totp/disable", s.requirePermission("project:read", s.authTOTPDisable))
	mux.Handle("POST /api/v1/auth/recovery-codes/regenerate", s.requirePermission("project:read", s.authRecoveryCodesRegenerate))
	mux.HandleFunc("POST /api/v1/auth/recovery-code/consume", s.authRecoveryCodeConsume)
	mux.HandleFunc("POST /api/v1/auth/password-reset/request", s.authPasswordResetRequest)
	mux.HandleFunc("POST /api/v1/auth/password-reset/confirm", s.authPasswordResetConfirm)
	mux.HandleFunc("POST /api/v1/auth/email-verification/request", s.authEmailVerificationRequest)
	mux.HandleFunc("POST /api/v1/auth/email-verification/confirm", s.authEmailVerificationConfirm)
}
