package httpapi

import (
	"net/http"
	"time"
)

func (s Server) registerPackageRoutesV1(mux *http.ServeMux) {
	mux.HandleFunc("POST /api/v1/admin/login", s.adminLogin)
	mux.Handle("GET /api/v1/admin/me", s.requirePermission("project:read", s.adminMe))
	mux.Handle("POST /api/v1/admin/logout", s.requirePermission("project:read", s.adminLogout))
	mux.Handle("GET /api/v1/admin/overview", s.requirePermission("project:read", s.adminOverview))
	mux.Handle("GET /api/v1/admin/users", s.requirePermission("users:manage", s.adminUsers))
	mux.Handle("POST /api/v1/admin/users", s.requirePermission("users:manage", s.adminUserCreate))
	mux.Handle("PATCH /api/v1/admin/users/{userId}", s.requireFreshAuth117("users:manage", "phishing-resistant", 5*time.Minute, s.adminUserUpdate))
	mux.Handle("POST /api/v1/admin/users/{userId}/password", s.requirePermission("users:manage", s.adminUserPassword))
	mux.Handle("POST /api/v1/admin/users/{userId}/disable", s.requirePermission("users:manage", s.adminUserDisable))
	mux.Handle("POST /api/v1/admin/users/{userId}/enable", s.requirePermission("users:manage", s.adminUserEnable))
	mux.Handle("GET /api/v1/admin/roles", s.requirePermission("users:manage", s.adminRoles))
	mux.Handle("GET /api/v1/admin/audit", s.requirePermission("audit:read", s.adminAudit))
	mux.Handle("GET /api/v1/admin/storage/health", s.requirePermission("project:read", s.adminStorageHealth))
	mux.Handle("GET /api/v1/desktop/extensions/catalog", s.requireDesktopExtensionAuth0209(s.desktopExtensionCatalog0209))
	mux.Handle("GET /api/v1/desktop/extensions/{extensionId}/ui", s.requireDesktopExtensionAuth0209(s.desktopExtensionEntrypoint0209))
	mux.Handle("POST /api/v1/desktop/extensions/{extensionId}/rpc", s.requireDesktopExtensionAuth0209(s.desktopExtensionRPC0209))
	mux.Handle("GET /api/v1/admin/extension-cli/catalog", s.requirePermission("extension:manage", s.extensionCLICatalog0209))
	mux.Handle("POST /api/v1/admin/extension-cli/{extensionId}/invoke", s.requirePermission("extension:manage", s.extensionCLIInvoke0209))
	mux.Handle("GET /api/v1/admin/extensions/catalog", s.requireAdminAuthenticated0208(s.adminExtensionCatalog0208))
	mux.Handle("GET /api/v1/admin/extensions/manager", s.requirePermission("extension:manage", s.adminExtensionManager0208))
	mux.Handle("GET /api/v1/admin/extensions/{extensionId}/ui", s.requireAdminAuthenticated0208(s.adminExtensionEntrypoint0208))
	mux.Handle("POST /api/v1/admin/extensions/{extensionId}/rpc", s.requireAdminAuthenticated0208(s.adminExtensionRPC0208))
	mux.Handle("GET /api/v1/admin/extensions", s.requirePermission("extension:manage", s.adminExtensions0201))
	mux.Handle("POST /api/v1/admin/extensions/versions", s.requirePermission("extension:manage", s.adminExtensionVersionRegister0201))
	mux.Handle("GET /api/v1/admin/extensions/{extensionId}", s.requirePermission("extension:manage", s.adminExtension0201))
	mux.Handle("GET /api/v1/admin/extensions/{extensionId}/versions", s.requirePermission("extension:manage", s.adminExtensionVersions0201))
	mux.Handle("GET /api/v1/admin/extensions/{extensionId}/versions/{version}", s.requirePermission("extension:manage", s.adminExtensionVersion0201))
	mux.Handle("GET /api/v1/admin/extension-trust/policy", s.requirePermission("extension:manage", s.extensionTrustPolicyGet02012))
	mux.Handle("PUT /api/v1/admin/extension-trust/policy", s.requireFreshAuth117("extension:manage", "mfa", 5*time.Minute, s.extensionTrustPolicyPut02012))
	mux.Handle("POST /api/v1/admin/extension-registry/publishers/{publisherId}/keys/{fingerprint}/revoke", s.requireFreshAuth117("extension:manage", "phishing-resistant", 5*time.Minute, s.extensionPublisherKeyRevoke02012))
	mux.Handle("GET /api/v1/admin/extension-quarantine", s.requirePermission("extension:manage", s.extensionQuarantineList02012))
	mux.Handle("POST /api/v1/admin/extension-quarantine/{quarantineId}/release", s.requireFreshAuth117("extension:manage", "mfa", 5*time.Minute, s.extensionQuarantineRelease02012))
	mux.Handle("GET /api/v1/admin/extension-emergency-disables", s.requirePermission("extension:manage", s.extensionEmergencyDisableList02012))
	mux.Handle("POST /api/v1/admin/extensions/{extensionId}/emergency-disable", s.requireFreshAuth117("extension:manage", "mfa", 5*time.Minute, s.extensionEmergencyDisable02012))
	mux.Handle("DELETE /api/v1/admin/extensions/{extensionId}/emergency-disable", s.requireFreshAuth117("extension:manage", "mfa", 5*time.Minute, s.extensionEmergencyClear02012))
	mux.Handle("GET /api/v1/admin/extension-recovery/export", s.requirePermission("extension:manage", s.extensionRecoveryExport02012))
	mux.Handle("POST /api/v1/admin/extension-recovery/import", s.requireFreshAuth117("extension:manage", "phishing-resistant", 5*time.Minute, s.extensionRecoveryImport02012))
	mux.Handle("POST /api/v1/admin/extension-recovery/backup", s.requireFreshAuth117("extension:manage", "mfa", 5*time.Minute, s.extensionRecoveryBackup02012))
	mux.Handle("POST /api/v1/admin/extension-recovery/restore", s.requireFreshAuth117("extension:manage", "phishing-resistant", 5*time.Minute, s.extensionRecoveryRestore02012))
	mux.Handle("GET /api/v1/admin/extension-capabilities", s.requirePermission("extension:manage", s.extensionCapabilityCatalog0207))
	mux.Handle("GET /api/v1/admin/extensions/{extensionId}/permissions", s.requirePermission("extension:manage", s.extensionPermissionState0207))
	mux.Handle("POST /api/v1/admin/extensions/{extensionId}/permissions", s.requireFreshAuth117("extension:manage", "mfa", 5*time.Minute, s.extensionPermissionGrant0207))
	mux.Handle("DELETE /api/v1/admin/extensions/{extensionId}/permissions/{permission}", s.requireFreshAuth117("extension:manage", "mfa", 5*time.Minute, s.extensionPermissionRevoke0207))
	mux.Handle("GET /api/v1/admin/extensions/{extensionId}/secrets", s.requirePermission("extension:manage", s.extensionSecretsList0207))
	mux.Handle("PUT /api/v1/admin/extensions/{extensionId}/secrets/{secretName}", s.requireFreshAuth117("extension:manage", "phishing-resistant", 5*time.Minute, s.extensionSecretPut0207))
	mux.Handle("DELETE /api/v1/admin/extensions/{extensionId}/secrets/{secretName}", s.requireFreshAuth117("extension:manage", "phishing-resistant", 5*time.Minute, s.extensionSecretDelete0207))
	mux.Handle("GET /api/v1/admin/extension-installs", s.requirePermission("extension:manage", s.extensionInstallList0204))
	mux.Handle("GET /api/v1/admin/extension-installs/{extensionId}", s.requirePermission("extension:manage", s.extensionInstallDetail0204))
	mux.Handle("POST /api/v1/admin/extension-installs/{extensionId}/install", s.requirePermission("extension:manage", s.extensionInstall0204))
	mux.Handle("POST /api/v1/admin/extension-installs/{extensionId}/enable", s.requirePermission("extension:manage", s.extensionEnable0204))
	mux.Handle("POST /api/v1/admin/extension-installs/{extensionId}/disable", s.requirePermission("extension:manage", s.extensionDisable0204))
	mux.Handle("POST /api/v1/admin/extension-installs/{extensionId}/uninstall", s.requireFreshAuth117("extension:manage", "mfa", 5*time.Minute, s.extensionUninstall0204))
	mux.Handle("POST /api/v1/admin/extension-installs/{extensionId}/update", s.requireFreshAuth117("extension:manage", "mfa", 5*time.Minute, s.extensionUpdate0204))
	mux.Handle("POST /api/v1/admin/extension-installs/{extensionId}/rollback", s.requireFreshAuth117("extension:manage", "mfa", 5*time.Minute, s.extensionRollback0204))
	mux.Handle("POST /api/v1/admin/extension-updates/plan", s.requirePermission("extension:manage", s.extensionUpdatePlan02011))
	mux.Handle("POST /api/v1/admin/extension-updates/apply", s.requireFreshAuth117("extension:manage", "mfa", 5*time.Minute, s.extensionUpdateApply02011))
	mux.Handle("GET /api/v1/admin/extension-updates/transactions/{transactionId}", s.requirePermission("extension:manage", s.extensionUpdateTransaction02011))
	mux.Handle("GET /api/v1/admin/extension-updates/pins", s.requirePermission("extension:manage", s.extensionUpdatePins02011))
	mux.Handle("PUT /api/v1/admin/extension-updates/pins/{extensionId}", s.requireFreshAuth117("extension:manage", "mfa", 5*time.Minute, s.extensionUpdatePinPut02011))
	mux.Handle("DELETE /api/v1/admin/extension-updates/pins/{extensionId}", s.requireFreshAuth117("extension:manage", "mfa", 5*time.Minute, s.extensionUpdatePinDelete02011))
	mux.Handle("GET /api/v1/admin/extension-events", s.requirePermission("extension:manage", s.eventBusStatus0206))
	mux.Handle("GET /api/v1/admin/extension-events/subscriptions", s.requirePermission("extension:manage", s.eventSubscriptions0206))
	mux.Handle("GET /api/v1/admin/extension-events/dead-letters", s.requirePermission("extension:manage", s.eventDeadLetters0206))
	mux.Handle("GET /api/v1/admin/extension-hosts", s.requirePermission("extension:manage", s.extensionHosts0205))
	mux.Handle("GET /api/v1/admin/extension-hosts/{extensionId}", s.requirePermission("extension:manage", s.extensionHostDetail0205))
	mux.Handle("GET /api/v1/admin/extension-hosts/{extensionId}/logs", s.requirePermission("extension:manage", s.extensionHostLogs0205))
	mux.Handle("POST /api/v1/admin/extension-hosts/{extensionId}/start", s.requirePermission("extension:manage", s.extensionHostStart0205))
	mux.Handle("POST /api/v1/admin/extension-hosts/{extensionId}/stop", s.requirePermission("extension:manage", s.extensionHostStop0205))
	mux.Handle("POST /api/v1/admin/extension-hosts/{extensionId}/restart", s.requirePermission("extension:manage", s.extensionHostRestart0205))
	mux.Handle("GET /api/v1/admin/extension-registry/publishers", s.requirePermission("extension:manage", s.extensionRegistryPublishers0203))
	mux.Handle("POST /api/v1/admin/extension-registry/publishers", s.requirePermission("extension:manage", s.extensionRegistryPublisherCreate0203))
	mux.Handle("GET /api/v1/admin/extension-registry/publishers/{publisherId}/keys", s.requirePermission("extension:manage", s.extensionRegistryPublisherKeys0203))
	mux.Handle("POST /api/v1/admin/extension-registry/publishers/{publisherId}/keys", s.requirePermission("extension:manage", s.extensionRegistryPublisherKeyCreate0203))
	mux.Handle("GET /api/v1/admin/extension-registry/extensions", s.requirePermission("extension:manage", s.extensionRegistrySearch0203))
	mux.Handle("POST /api/v1/admin/extension-registry/publish", s.requireFreshAuth117("extension:manage", "mfa", 5*time.Minute, s.extensionRegistryPublish0203))
	mux.Handle("GET /api/v1/admin/extension-registry/extensions/{extensionId}", s.requirePermission("extension:manage", s.extensionRegistryExtension0203))
	mux.Handle("GET /api/v1/admin/extension-registry/extensions/{extensionId}/versions/{version}", s.requirePermission("extension:manage", s.extensionRegistryVersion0203))
	mux.Handle("GET /api/v1/admin/extension-registry/extensions/{extensionId}/versions/{version}/artifact", s.requirePermission("extension:manage", s.extensionRegistryArtifact0203))
	mux.Handle("POST /api/v1/admin/extension-registry/extensions/{extensionId}/versions/{version}/yank", s.requireFreshAuth117("extension:manage", "mfa", 5*time.Minute, s.extensionRegistryYank0203))
	mux.Handle("PUT /api/v1/admin/extension-registry/extensions/{extensionId}/channels/{channel}", s.requirePermission("extension:manage", s.extensionRegistryChannelSet0203))
	mux.Handle("POST /api/v1/admin/extension-registry/extensions/{extensionId}/versions/{version}/install", s.requirePermission("extension:manage", s.extensionRegistryInstall0203))
	mux.Handle("POST /api/v1/admin/projects/{projectId}/publish", s.requireFreshAuth117("release:publish", "mfa", 5*time.Minute, s.adminPublish))
	mux.Handle("POST /api/v1/admin/projects/{projectId}/versions", s.requirePermission("release:prepare", s.adminVersionCreate))
	mux.Handle("PUT /api/v1/admin/projects/{projectId}/versions/{versionId}/manifest", s.requirePermission("release:prepare", s.adminVersionManifestUpdate))
	mux.Handle("POST /api/v1/admin/projects/{projectId}/versions/{versionId}/files", s.requirePermission("file:write", s.adminFileUpload))
	mux.Handle("POST /api/v1/admin/projects/{projectId}/versions/{versionId}/publish", s.requireFreshAuth117("release:publish", "mfa", 5*time.Minute, s.adminVersionPublish))
	mux.Handle("GET /api/v1/admin/projects/{projectId}/export", s.requirePermission("project:read", s.adminProjectExport))
	mux.Handle("POST /api/v1/admin/projects/import", s.requirePermission("project:write", s.adminProjectImport))
	mux.Handle("POST /api/v1/telemetry/events", s.requirePermission("project:read", s.telemetryEvent))
	mux.Handle("POST /api/v1/crash-reports", s.requirePermission("project:read", s.crashReport))
	mux.Handle("POST /api/v1/packages", s.requirePermission("release:prepare", s.packageCreate))
	mux.Handle("GET /api/v1/packages/{packageId}", s.requirePermission("project:read", s.packageGet))
	mux.Handle("POST /api/v1/packages/{packageId}/files", s.requirePermission("file:write", s.packageUploadFile))
	mux.Handle("POST /api/v1/packages/{packageId}/validate", s.requirePermission("release:prepare", s.packageValidate))
	mux.Handle("POST /api/v1/packages/{packageId}/sign", s.requireFreshAuth117("release:prepare", "phishing-resistant", 5*time.Minute, s.packageSign))
	mux.Handle("POST /api/v1/packages/{packageId}/stage", s.requirePermission("release:prepare", s.packageStage))
	mux.Handle("POST /api/v1/packages/{packageId}/smoke-test", s.requirePermission("release:prepare", s.packageSmoke))
	mux.Handle("POST /api/v1/packages/{packageId}/publish", s.requireFreshAuth117("release:publish", "mfa", 5*time.Minute, s.packagePublishProduct))
	mux.Handle("POST /api/v1/channels/{channel}/rollback", s.requireFreshAuth117("release:publish", "mfa", 5*time.Minute, s.channelRollbackProduct))
	mux.Handle("GET /api/v1/storage/delivery-policy", s.requirePermission("project:read", s.storageDeliveryPolicy))
}
